# Generated by Django 4.2.7 on 2023-12-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_testresult_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='section',
            field=models.CharField(choices=[('Basic', 'Basic'), ('BasicHTML', 'BasicHTML'), ('BasicPHP', 'BasicPHP'), ('Intermediate', 'Intermediate'), ('IntermediateHTML', 'IntermediateHTML'), ('IntermediatePHP', 'IntermediatePHP'), ('Advanced', 'Advanced'), ('AdvancedHTML', 'AdvancedHTML'), ('AdvancedPHP', 'AdvancedPHP')], default='Basic', max_length=100),
        ),
    ]
