# Generated by Django 4.2.10 on 2024-02-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_testresult_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='is_active_fields',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
