# Generated by Django 5.0.2 on 2024-03-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_testresult_correct_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='correct_answers',
            field=models.TextField(blank=True),
        ),
    ]
