# Generated by Django 5.0.2 on 2024-03-12 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_remove_testresult_correct_answers_correctanswers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctanswers',
            name='date_saved',
        ),
    ]
