# Generated by Django 5.0.2 on 2024-07-14 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_rename_course_courseregistration_course_id'),
        ('exam', '0008_remove_correctanswers_date_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.coursedb'),
        ),
    ]
