# Generated by Django 5.0.2 on 2024-07-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0006_watchhistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchhistory',
            name='course_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
