# Generated by Django 5.0.2 on 2024-07-14 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0008_rename_course_name_watchhistory_course_id'),
        ('accounts', '0027_coursedb_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchhistory',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.coursedb'),
        ),
    ]
