# Generated by Django 5.0.2 on 2024-07-20 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0011_rename_video_comment_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='video',
        ),
    ]
