# Generated by Django 4.2.7 on 2023-12-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_custuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='custuser',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='custuser',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
