# Generated by Django 5.0.2 on 2024-04-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_custuser_is_active_adv_custuser_is_active_basic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custuser',
            name='is_faculty',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='custuser',
            name='is_student',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
