# Generated by Django 5.0.2 on 2024-06-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_coursedb_courseregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='custuser',
            name='Course',
            field=models.CharField(blank=True, choices=[('Python', 'Python'), ('HTML', 'HTML'), ('PHP', 'PHP')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='custuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=100, null=True),
        ),
    ]
