# Generated by Django 5.0.2 on 2024-06-10 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pdfnotes',
        ),
    ]
