# Generated by Django 5.0.2 on 2024-06-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_delete_pdfnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
