# Generated by Django 5.0.2 on 2024-06-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_uploadedfile_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='custuser',
            name='is_hr',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
