# Generated by Django 5.0.2 on 2024-06-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='image_icon',
            field=models.ImageField(blank=True, null=True, upload_to='placement_icons/'),
        ),
        migrations.AddField(
            model_name='placement',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='qualification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
