# Generated by Django 5.0.2 on 2024-06-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='skills',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
