# Generated by Django 5.0.2 on 2024-06-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_placement_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
