# Generated by Django 5.0.2 on 2024-06-14 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_jobapplication_list_delete_jobapplication'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobApplication_list',
            new_name='JobApplication',
        ),
    ]
