# Generated by Django 5.0.2 on 2024-07-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_rename_jobapplication_list_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedb',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
