# Generated by Django 5.0.2 on 2024-07-14 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_coursedb_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseregistration',
            old_name='course',
            new_name='course_id',
        ),
    ]
