# Generated by Django 5.0.2 on 2024-07-14 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_rename_course_courseregistration_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseregistration',
            old_name='course_id',
            new_name='course',
        ),
    ]
