# Generated by Django 5.0.2 on 2024-07-14 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_rename_course_id_courseregistration_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseregistration',
            old_name='course',
            new_name='course_id',
        ),
    ]
