# Generated by Django 5.0.2 on 2024-07-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_rename_course_courseregistration_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
