# Generated by Django 5.0.2 on 2024-07-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_custuser_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custuser',
            name='Course',
            field=models.CharField(blank=True, choices=[('Python', 'Python'), ('HTML', 'HTML'), ('PHP', 'PHP'), ('None', 'None')], default='None', max_length=10, null=True),
        ),
    ]
